version: "3"

networks:
  mongodb_dbs:
    external: true

services:
  tg_personal_bot:
    container_name: tg_personal_bot
    restart: always
    build: ./
    ports:
      - "8002:8002"
    networks:
      - mongodb_dbs
