version: "3"

networks:
  monitoring_stack_loki:
    external: true

services:
  tg_personal_bot:
    container_name: tg_personal_bot
    restart: always
    build: ./
    ports:
      - "8002:8002"
    networks:
      - monitoring_stack_loki
    depends_on:
      - mongoDB

  mongoDB:
    container_name: mongoDB
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - monitoring_stack_loki