version: "3"

networks:
  monitoring_stack_loki:
    external: true

services:
  tg_personal_bot:
    container_name: tg_personal_bot
    restart: always
    build: ./
    ports:
      - "8002:8002"
    links:
      - fin_postgresql_db:fin_postgresql_db
    depends_on:
      - fin_postgresql_db
    networks:
      - monitoring_stack_loki

  fin_postgresql_db:
    container_name: fin_postgresql_db
    restart: always
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e99XkkL1VmuZ
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    networks:
      - monitoring_stack_loki
