version: "3"

networks:
  local:
    external: false

services:
  tg_personal_bot:
    container_name: tg_personal_bot
    restart: always
    build: ./
    ports:
      - "8002:8002"
    depends_on:
      - mongoDB
    networks:
      - local

  mongoDB:
    container_name: mongoDB
    image: mongo:4.4.6
    restart: always
    ports:
      - "27017:27017"
    networks:
      - local